version: '3.0'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: spring
      MYSQL_ROOT_PASSWORD: spring
    ports:
    - 3306:3306
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/